apiVersion: v1
kind: Secret
metadata:
  name: shopease-secrets
  labels:
    app: shopease
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: k8s_root_password
  MYSQL_PASSWORD: k8s_db_password
  JWT_SECRET: k8s-super-secret-jwt-key-change-in-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shopease-config
  labels:
    app: shopease
data:
  MYSQL_DATABASE: ecomdb
  MYSQL_USER: shopease
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/ecomdb?useSSL=false&allowPublicKeyRetrieval=true
  REACT_APP_API_URL: http://backend-service:8080
